import React, { useEffect, useState } from "react";
import Head from "next/head";
import Question1 from "../component/question1";
import Question2 from "../component/question2";
import Question3 from "../component/question3";

export default function Home() {
  const [question, setQuestion] = useState("q1");

  return (
    <div>
      <Head>
        <title>Refin HomeWork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous"
        />
      </Head>
      <div>
        <div className="d-flex justify-content-around mb-5">
          <h3 onClick={() => setQuestion("q1")} className="pointer">
            Question 1
          </h3>
          <h3 onClick={() => setQuestion("q2")} className="pointer">
            Question 2
          </h3>
          <h3 onClick={() => setQuestion("q3")} className="pointer">
            Question 3
          </h3>
        </div>
        {question === "q1" && <Question1 />}
        {question === "q2" && <Question2 />}
        {question === "q3" && <Question3 />}
      </div>
    </div>
  );
}
